name: CI
on:
  pull_request:
    branches:
      - master
      - feature
jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Deps
        run: yarn
      - name: Build
        run: yarn build
